name: Python application CI

on:
  push:
    branches: [ main, master ] # Triggers the workflow on push events to main or master
  pull_request:
    branches: [ main, master ] # Also triggers on pull requests to main or master

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the runner environment

    strategy:
      matrix:
        python-version: ["3.10"] # Define the Python version(s) to use.
                                  # Match this with your project's environment.yml

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # If your project primarily uses environment.yml for dependencies for the app itself:
        # You might need to install conda and create the environment here if pytest
        # needs the full app environment.
        # For now, this installs flake8, pytest, and dependencies from requirements.txt
        # (The starter kit for this FastAPI project *does* have a requirements.txt)

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
